### ISSUE TITLE
**TESTING** USER STORY: Testing and validating all the code.

### ISSUE THREAD

**Issue by SoroushGReza** [SoroushGReza/movies-database#11]
As a *Developer** I can **test the app and all it's functions to make sure that everything works as it should, and make sure it follows the criteria**.

**Tasks***:

- [ ] Task 1: Validate all HTML files
- [ ] Task2 : Validate all CSS files
- [ ]  Task: Validate all Python files
- [ ] Task 4: Validate all JS files
- [ ] Task 5: Make sure verything is documented in README.md
- [ ] Task 6: Resolve all workspace warnings and errors.
