### ISSUE TITLE
USER STOR: View and manage user profile

### ISSUE THREAD

**Issue by SoroushGReza** [SoroushGReza/movies-database#3]
As a **User**, I can **View and Edit my Profile**, so that **I can manage my personal information**.

**Tasks:**

- [x] Task 1: Create a profile view page.
- [x] Task 2: Display user's current information on the profile page.
- [x] Task 3: Implement edit button on the profile page.
- [x] Task 4: Create a form for editing user profile information.
- [x] Task 5: Add validation to ensure proper data input.
- [x] Task 6: Provide feedback to the user after successful editing.
