### ISSUE TITLE
USER STORY: Register, Login, Logout

### ISSUE THREAD

**Issue by SoroushGReza** [SoroushGReza/movies-database#6]
As a **User**, I can **Register, Login and Logout**, so that **I can access my personal info and manage my account**.

**Tasks**
- [x] Implement user login functionality.
- [x] Implement user registration functionality.
- [x] Implement user logout functionality.
