### ISSUE TITLE
USER STORY: Email Confirmations

### ISSUE THREAD

**Issue by SoroushGReza** [SoroushGReza/movies-database#9]
As a **User**, I can **receive email confirmations**, so that **I can be notified of important account activities.**

**Tasks**:

- [ ] Task 1: Send a welcome email when registering.
- [ ] Task 2: Send confirmation when the password has been changed.
- [ ] Task 3: Send confirmation when the account has been deleted.
